### ISSUE TITLE
Make a report form

### ISSUE THREAD

**Issue by Bohjaangles** [jakinyang/minaa#15]
adding all required fields for input

basic formatting so it looks quarter way decent

ensure that dropdowns don't mess the rest of the layout

**Comment by Bohjaangles** [comment]
This is most of the way there. Just need the image to render. Am unable to continue as the branch this is on, I can no longer render for testing purposes as there are changes made to other files I was not working on that are incompatible with my my phone ability to build the expo file

**Comment by jakinyang** [comment]
The report form was mostly integrated and now we just have to implement the client to interact with the graphql API @Bohjaangles @Benjamin0203
