### ISSUE TITLE
Report history screen

### ISSUE THREAD

**Issue by Bohjaangles** [jakinyang/minaa#20]
a screen that dynamically lists all the reports made by a user,

**Comment by Bohjaangles** [comment]
- got the carousel working
 - the carousel currently does not display anything other than white cards
 - the carousel is the correct length
 - Carousel cards are getting mock data as a prop, so the displaying only white is a bug to solve

**Comment by Bohjaangles** [comment]
- carousel now shows cards with accurate to mock data data, including a title, body, and image
- refomated the cards so they are a consistent size when browsing carousel and does not overflow

**Comment by jakinyang** [comment]
Great job with the carousel integration! I'm thinking of maybe moving that into the main profile page entirely! @Bohjaangles

**Comment by Benjamin0203** [comment]
The carousel looks fire, like the design and functionality
