### ISSUE TITLE
test/newMarkerBen: fix marker rendering on map

### ISSUE THREAD

**Issue by jakinyang** [jakinyang/minaa#25]
Fixing the rendering and gesture issues with new pins on the map

**Comment by jakinyang** [comment]
Will continue pair programming to address potential issues with state management.

**Comment by Benjamin0203** [comment]
Thanks for helping out! @jakinyang problem solved

**Comment by jakinyang** [comment]
You did a great job @Benjamin0203 this is a huge win for the project!

**Comment by Bohjaangles** [comment]
Looks good guys, good work!
